default_install_hook_types: ["pre-commit", "pre-push"]

repos:
  - repo: local
    hooks:
      - id: just-format
        name: Format code (Just)
        entry: just format
        language: system
        pass_filenames: false
        always_run: true

      - id: just-lint
        name: Lint code (Just)
        entry: just lint
        language: system
        pass_filenames: false
        always_run: true
